stages:
  - build
  - deploy
  - loading-tests-local

image:
  name: ubuntu:latest

build:
  stage: build
  script:
    - echo "building my application in ubuntu container..."

deploy:
  stage: deploy
  script:
    - echo "deploying my application in ubuntu container..."

loading-tests-local:
  image:
    name: grafana/k6:latest
    entrypoint: ['']
  stage: loading-tests-local
  script:
    - echo "executing local k6 in k6 container..."
    - k6 run dist/get-200-status-test.js